// Real astronomical data for Bosco's Solar System
// Orbital periods in Earth days. Distances in AU. Diameters in km.
// Images are NASA public-domain via Wikimedia Commons.

window.SOLAR_DATA = {
  sun: {
    id: 'sun',
    name: 'The Sun',
    kind: 'Star (G-type Yellow Dwarf)',
    diameter_km: 1392700,
    surface_temp_c: 5500,
    color: '#ffb547',
    glowColor: '#ffd27a',
    image: 'https://upload.wikimedia.org/wikipedia/commons/b/b4/The_Sun_by_the_Atmospheric_Imaging_Assembly_of_NASA%27s_Solar_Dynamics_Observatory_-_20100819.jpg',
    blurb: 'The Sun is a giant ball of glowing gas at the center. It gives us light and warmth.',
    wowFact: 'The Sun is so big, more than a million Earths could fit inside it!',
    facts: [
      { label: 'What is it', value: 'A star — a huge ball of hot gas' },
      { label: 'How big', value: '109 times wider than Earth' },
      { label: 'How hot', value: '5,500°C on the surface' },
      { label: 'Age', value: '4.6 billion years old' },
    ],
  },
  planets: [
    {
      id: 'mercury',
      name: 'Mercury',
      order: 1,
      kind: 'Terrestrial Planet',
      // Visual layout (compressed)
      orbitAU_real: 0.39,
      orbitAU_compressed: 0.18,
      phase: 0.4,
      diameter_km: 4879,
      visualRadius: 6,
      // Color and rendering
      color: '#a89282',
      tint: '#8a7868',
      image: 'https://upload.wikimedia.org/wikipedia/commons/4/4a/Mercury_in_color_-_Prockter07_centered.jpg',
      // Real motion
      orbitalPeriod_days: 87.97,
      rotationPeriod_days: 58.65,
      axialTilt_deg: 0.03,
      // Copy
      blurb: 'The smallest planet, closest to the Sun. It is rocky and covered in craters.',
      wowFact: 'A day on Mercury lasts almost 59 Earth days — longer than its year!',
      moons: 0,
      hasRings: false,
      facts: [
        { label: 'Position', value: '1st from the Sun' },
        { label: 'Size', value: 'Smallest planet' },
        { label: 'A year', value: '88 Earth days' },
        { label: 'A day', value: '59 Earth days' },
        { label: 'Moons', value: '0' },
        { label: 'Temperature', value: '−180°C to 430°C' },
      ],
    },
    {
      id: 'venus',
      name: 'Venus',
      order: 2,
      kind: 'Terrestrial Planet',
      orbitAU_real: 0.72,
      orbitAU_compressed: 0.27,
      phase: 2.1,
      diameter_km: 12104,
      visualRadius: 11,
      color: '#e8c485',
      tint: '#d4a866',
      image: 'https://upload.wikimedia.org/wikipedia/commons/e/e5/Venus-real_color.jpg',
      orbitalPeriod_days: 224.7,
      rotationPeriod_days: -243.02, // negative = retrograde
      axialTilt_deg: 177.4,
      blurb: 'The hottest planet, wrapped in thick yellow clouds. It spins backwards!',
      wowFact: 'Venus spins the wrong way — the Sun rises in the west and sets in the east.',
      moons: 0,
      hasRings: false,
      facts: [
        { label: 'Position', value: '2nd from the Sun' },
        { label: 'Size', value: 'Similar to Earth' },
        { label: 'A year', value: '225 Earth days' },
        { label: 'A day', value: '243 Earth days' },
        { label: 'Moons', value: '0' },
        { label: 'Temperature', value: '465°C — hottest!' },
      ],
    },
    {
      id: 'earth',
      name: 'Earth',
      order: 3,
      kind: 'Our Home',
      orbitAU_real: 1.00,
      orbitAU_compressed: 0.37,
      phase: 4.2,
      diameter_km: 12742,
      visualRadius: 12,
      color: '#5b9fd9',
      tint: '#3d7bb0',
      image: 'https://upload.wikimedia.org/wikipedia/commons/9/97/The_Earth_seen_from_Apollo_17.jpg',
      orbitalPeriod_days: 365.25,
      rotationPeriod_days: 1.0,
      axialTilt_deg: 23.44,
      blurb: 'Our home! The only planet we know with oceans, forests, animals — and you.',
      wowFact: 'Earth is the only place in the whole solar system with life.',
      moons: 1,
      hasRings: false,
      moon: {
        name: 'The Moon',
        image: 'https://upload.wikimedia.org/wikipedia/commons/e/e1/FullMoon2010.jpg',
        orbitalPeriod_days: 27.32,
        diameter_km: 3474,
        blurb: "Earth's only moon. It is rocky and covered in craters from space rocks.",
      },
      facts: [
        { label: 'Position', value: '3rd from the Sun' },
        { label: 'Size', value: '5th largest planet' },
        { label: 'A year', value: '365.25 days' },
        { label: 'A day', value: '24 hours' },
        { label: 'Moons', value: '1 — the Moon' },
        { label: 'Surface', value: '71% ocean, 29% land' },
      ],
    },
    {
      id: 'mars',
      name: 'Mars',
      order: 4,
      kind: 'Terrestrial Planet',
      orbitAU_real: 1.52,
      orbitAU_compressed: 0.48,
      phase: 0.9,
      diameter_km: 6779,
      visualRadius: 9,
      color: '#c66a3f',
      tint: '#a35430',
      image: 'https://upload.wikimedia.org/wikipedia/commons/0/02/OSIRIS_Mars_true_color.jpg',
      orbitalPeriod_days: 686.97,
      rotationPeriod_days: 1.03,
      axialTilt_deg: 25.19,
      blurb: 'The red planet. It is rusty, dusty, and has the tallest volcano in the solar system.',
      wowFact: 'Mars has a volcano called Olympus Mons — three times taller than Mount Everest!',
      moons: 2,
      hasRings: false,
      facts: [
        { label: 'Position', value: '4th from the Sun' },
        { label: 'Size', value: 'Half the size of Earth' },
        { label: 'A year', value: '687 Earth days' },
        { label: 'A day', value: '24h 37min' },
        { label: 'Moons', value: '2 — Phobos & Deimos' },
        { label: 'Why red', value: 'Iron rust on the surface' },
      ],
    },
    {
      id: 'jupiter',
      name: 'Jupiter',
      order: 5,
      kind: 'Gas Giant',
      orbitAU_real: 5.20,
      orbitAU_compressed: 0.62,
      phase: 3.5,
      diameter_km: 139820,
      visualRadius: 26,
      color: '#d4a574',
      tint: '#b8845a',
      image: 'https://upload.wikimedia.org/wikipedia/commons/2/2b/Jupiter_and_its_shrunken_Great_Red_Spot.jpg',
      orbitalPeriod_days: 4332.59,
      rotationPeriod_days: 0.41,
      axialTilt_deg: 3.13,
      blurb: 'The biggest planet — a giant ball of gas with a huge red storm bigger than Earth.',
      wowFact: "Jupiter is so big that all the other planets could fit inside it!",
      moons: 95,
      hasRings: false,
      facts: [
        { label: 'Position', value: '5th from the Sun' },
        { label: 'Size', value: 'BIGGEST planet' },
        { label: 'A year', value: '12 Earth years' },
        { label: 'A day', value: '10 hours (fastest spin)' },
        { label: 'Moons', value: '95 known moons' },
        { label: 'Famous for', value: 'The Great Red Spot storm' },
      ],
    },
    {
      id: 'saturn',
      name: 'Saturn',
      order: 6,
      kind: 'Gas Giant',
      orbitAU_real: 9.58,
      orbitAU_compressed: 0.76,
      phase: 0.3,
      diameter_km: 116460,
      visualRadius: 22,
      color: '#e8c98f',
      tint: '#c9a86c',
      image: 'https://upload.wikimedia.org/wikipedia/commons/c/c7/Saturn_during_Equinox.jpg',
      orbitalPeriod_days: 10759.22,
      rotationPeriod_days: 0.45,
      axialTilt_deg: 26.73,
      blurb: 'The ringed planet. Saturn has beautiful rings made of ice and rock.',
      wowFact: "Saturn's rings are made of billions of pieces of ice — some as small as dust, some as big as houses.",
      moons: 146,
      hasRings: true,
      facts: [
        { label: 'Position', value: '6th from the Sun' },
        { label: 'Size', value: '2nd biggest planet' },
        { label: 'A year', value: '29 Earth years' },
        { label: 'A day', value: '10.7 hours' },
        { label: 'Moons', value: '146 known moons' },
        { label: 'Famous for', value: 'Its giant icy rings' },
      ],
    },
    {
      id: 'uranus',
      name: 'Uranus',
      order: 7,
      kind: 'Ice Giant',
      orbitAU_real: 19.18,
      orbitAU_compressed: 0.88,
      phase: 3.2,
      diameter_km: 50724,
      visualRadius: 15,
      color: '#a8d8e0',
      tint: '#7eb8c4',
      image: 'https://upload.wikimedia.org/wikipedia/commons/3/3d/Uranus2.jpg',
      orbitalPeriod_days: 30688.5,
      rotationPeriod_days: -0.72, // retrograde
      axialTilt_deg: 97.77,
      blurb: 'A frozen blue planet that is tipped on its side and rolls as it orbits.',
      wowFact: 'Uranus is tipped over and rolls around the Sun like a ball!',
      moons: 27,
      hasRings: true,
      facts: [
        { label: 'Position', value: '7th from the Sun' },
        { label: 'Size', value: '3rd biggest planet' },
        { label: 'A year', value: '84 Earth years' },
        { label: 'A day', value: '17 hours' },
        { label: 'Moons', value: '27' },
        { label: 'Special', value: 'Spins on its side' },
      ],
    },
    {
      id: 'neptune',
      name: 'Neptune',
      order: 8,
      kind: 'Ice Giant',
      orbitAU_real: 30.07,
      orbitAU_compressed: 1.00,
      phase: 5.4,
      diameter_km: 49244,
      visualRadius: 14,
      color: '#4a6fc7',
      tint: '#3354a8',
      image: 'https://upload.wikimedia.org/wikipedia/commons/5/56/Neptune_Full.jpg',
      orbitalPeriod_days: 60182,
      rotationPeriod_days: 0.67,
      axialTilt_deg: 28.32,
      blurb: 'The farthest, windiest planet. Deep blue with the strongest winds in the solar system.',
      wowFact: 'Neptune has winds that blow 2,000 km/h — five times faster than a hurricane!',
      moons: 14,
      hasRings: true,
      facts: [
        { label: 'Position', value: '8th from the Sun' },
        { label: 'Size', value: '4th biggest planet' },
        { label: 'A year', value: '165 Earth years' },
        { label: 'A day', value: '16 hours' },
        { label: 'Moons', value: '14' },
        { label: 'Famous for', value: 'Strongest winds in space' },
      ],
    },
  ],
  dwarf: {
    pluto: {
      id: 'pluto',
      name: 'Pluto',
      order: 9,
      kind: 'Dwarf Planet',
      orbitAU_real: 39.48,
      orbitAU_compressed: 1.12,
      phase: 1.5,
      diameter_km: 2376,
      visualRadius: 5,
      color: '#c9a98a',
      tint: '#a88a6c',
      image: 'https://upload.wikimedia.org/wikipedia/commons/e/e0/Pluto_in_True_Color_-_High-Res.jpg',
      orbitalPeriod_days: 90560,
      rotationPeriod_days: -6.39,
      axialTilt_deg: 122.53,
      blurb: 'A tiny, icy world far from the Sun. It used to be called a planet — now it is a "dwarf planet".',
      wowFact: 'One year on Pluto is 248 Earth years long. If you were born on Pluto, you would never have a birthday!',
      moons: 5,
      hasRings: false,
      facts: [
        { label: 'Type', value: 'Dwarf Planet' },
        { label: 'Size', value: 'Smaller than our Moon' },
        { label: 'A year', value: '248 Earth years' },
        { label: 'A day', value: '6.4 Earth days' },
        { label: 'Moons', value: '5 — biggest is Charon' },
        { label: 'Discovered', value: '1930' },
      ],
    },
  },
};
